/**
 * generated by Xtext 2.12.0
 */
package fr.idmteam1.idmproject.dronedsl.droneDSLLib;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.DroneDSLLibFactory
 * @model kind="package"
 * @generated
 */
public interface DroneDSLLibPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "droneDSLLib";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.idmteam1.fr/idmproject/dronedsl/DroneDSLLib";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "droneDSLLib";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DroneDSLLibPackage eINSTANCE = fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.ModelImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Fonctions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__FONCTIONS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.PourcentExpImpl <em>Pourcent Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.PourcentExpImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getPourcentExp()
   * @generated
   */
  int POURCENT_EXP = 19;

  /**
   * The number of structural features of the '<em>Pourcent Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POURCENT_EXP_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.PourcentConstImpl <em>Pourcent Const</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.PourcentConstImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getPourcentConst()
   * @generated
   */
  int POURCENT_CONST = 1;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POURCENT_CONST__VAL = POURCENT_EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Pourcent Const</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POURCENT_CONST_FEATURE_COUNT = POURCENT_EXP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.StatementImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 11;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.MonterImpl <em>Monter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.MonterImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getMonter()
   * @generated
   */
  int MONTER = 2;

  /**
   * The feature id for the '<em><b>Duree</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONTER__DUREE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Vitesse verticale</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONTER__VITESSE_VERTICALE = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Monter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MONTER_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DescendreImpl <em>Descendre</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DescendreImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getDescendre()
   * @generated
   */
  int DESCENDRE = 3;

  /**
   * The feature id for the '<em><b>Duree</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCENDRE__DUREE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Vitesse verticale</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCENDRE__VITESSE_VERTICALE = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Descendre</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCENDRE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.AvancerImpl <em>Avancer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.AvancerImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getAvancer()
   * @generated
   */
  int AVANCER = 4;

  /**
   * The feature id for the '<em><b>Duree</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVANCER__DUREE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Vitesse deplacement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVANCER__VITESSE_DEPLACEMENT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Avancer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVANCER_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.ReculerImpl <em>Reculer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.ReculerImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getReculer()
   * @generated
   */
  int RECULER = 5;

  /**
   * The feature id for the '<em><b>Duree</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECULER__DUREE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Vitesse deplacement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECULER__VITESSE_DEPLACEMENT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Reculer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECULER_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.GaucheImpl <em>Gauche</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.GaucheImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getGauche()
   * @generated
   */
  int GAUCHE = 6;

  /**
   * The feature id for the '<em><b>Duree</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAUCHE__DUREE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Vitesse deplacement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAUCHE__VITESSE_DEPLACEMENT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Gauche</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAUCHE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroiteImpl <em>Droite</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroiteImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getDroite()
   * @generated
   */
  int DROITE = 7;

  /**
   * The feature id for the '<em><b>Duree</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROITE__DUREE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Vitesse deplacement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROITE__VITESSE_DEPLACEMENT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Droite</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROITE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.PauseImpl <em>Pause</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.PauseImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getPause()
   * @generated
   */
  int PAUSE = 8;

  /**
   * The feature id for the '<em><b>Duree</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAUSE__DUREE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Pause</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAUSE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RotationGaucheImpl <em>Rotation Gauche</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RotationGaucheImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getRotationGauche()
   * @generated
   */
  int ROTATION_GAUCHE = 9;

  /**
   * The feature id for the '<em><b>Duree</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATION_GAUCHE__DUREE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Vitesse rotation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATION_GAUCHE__VITESSE_ROTATION = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Rotation Gauche</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATION_GAUCHE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RotationDroiteImpl <em>Rotation Droite</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RotationDroiteImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getRotationDroite()
   * @generated
   */
  int ROTATION_DROITE = 10;

  /**
   * The feature id for the '<em><b>Duree</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATION_DROITE__DUREE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Vitesse rotation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATION_DROITE__VITESSE_ROTATION = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Rotation Droite</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATION_DROITE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.FonctionRefImpl <em>Fonction Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.FonctionRefImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getFonctionRef()
   * @generated
   */
  int FONCTION_REF = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONCTION_REF__NAME = 0;

  /**
   * The number of structural features of the '<em>Fonction Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONCTION_REF_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.FonctionDeclImpl <em>Fonction Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.FonctionDeclImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getFonctionDecl()
   * @generated
   */
  int FONCTION_DECL = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONCTION_DECL__NAME = FONCTION_REF__NAME;

  /**
   * The feature id for the '<em><b>A</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONCTION_DECL__A = FONCTION_REF_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>B</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONCTION_DECL__B = FONCTION_REF_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONCTION_DECL__BODY = FONCTION_REF_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Fonction Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONCTION_DECL_FEATURE_COUNT = FONCTION_REF_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.FonctionExterneImpl <em>Fonction Externe</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.FonctionExterneImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getFonctionExterne()
   * @generated
   */
  int FONCTION_EXTERNE = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONCTION_EXTERNE__NAME = FONCTION_REF__NAME;

  /**
   * The number of structural features of the '<em>Fonction Externe</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONCTION_EXTERNE_FEATURE_COUNT = FONCTION_REF_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.FonctionCallImpl <em>Fonction Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.FonctionCallImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getFonctionCall()
   * @generated
   */
  int FONCTION_CALL = 14;

  /**
   * The feature id for the '<em><b>Func</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONCTION_CALL__FUNC = 0;

  /**
   * The number of structural features of the '<em>Fonction Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONCTION_CALL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.VarDeclImpl <em>Var Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.VarDeclImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getVarDecl()
   * @generated
   */
  int VAR_DECL = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Var Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECL_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.PourcentDeclImpl <em>Pourcent Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.PourcentDeclImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getPourcentDecl()
   * @generated
   */
  int POURCENT_DECL = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POURCENT_DECL__NAME = VAR_DECL__NAME;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POURCENT_DECL__VAL = VAR_DECL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Pourcent Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POURCENT_DECL_FEATURE_COUNT = VAR_DECL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.IntDeclImpl <em>Int Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.IntDeclImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getIntDecl()
   * @generated
   */
  int INT_DECL = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_DECL__NAME = VAR_DECL__NAME;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_DECL__VAL = VAR_DECL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_DECL_FEATURE_COUNT = VAR_DECL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.IntExpImpl <em>Int Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.IntExpImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getIntExp()
   * @generated
   */
  int INT_EXP = 23;

  /**
   * The number of structural features of the '<em>Int Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_EXP_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RefIntVarImpl <em>Ref Int Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RefIntVarImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getRefIntVar()
   * @generated
   */
  int REF_INT_VAR = 20;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REF_INT_VAR__VAR = INT_EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ref Int Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REF_INT_VAR_FEATURE_COUNT = INT_EXP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RefPourcentVarImpl <em>Ref Pourcent Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RefPourcentVarImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getRefPourcentVar()
   * @generated
   */
  int REF_POURCENT_VAR = 21;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REF_POURCENT_VAR__VAR = POURCENT_EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ref Pourcent Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REF_POURCENT_VAR_FEATURE_COUNT = POURCENT_EXP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.IntConstanteImpl <em>Int Constante</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.IntConstanteImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getIntConstante()
   * @generated
   */
  int INT_CONSTANTE = 22;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_CONSTANTE__VAL = INT_EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Constante</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_CONSTANTE_FEATURE_COUNT = INT_EXP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.MDImpl <em>MD</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.MDImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getMD()
   * @generated
   */
  int MD = 24;

  /**
   * The number of structural features of the '<em>MD</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MD_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.GDrImpl <em>GDr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.GDrImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getGDr()
   * @generated
   */
  int GDR = 25;

  /**
   * The number of structural features of the '<em>GDr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GDR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RGRDImpl <em>RGRD</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RGRDImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getRGRD()
   * @generated
   */
  int RGRD = 26;

  /**
   * The number of structural features of the '<em>RGRD</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RGRD_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.ARImpl <em>AR</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.ARImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getAR()
   * @generated
   */
  int AR = 27;

  /**
   * The number of structural features of the '<em>AR</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.ParalleleImpl <em>Parallele</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.ParalleleImpl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getParallele()
   * @generated
   */
  int PARALLELE = 28;

  /**
   * The feature id for the '<em><b>A</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARALLELE__A = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>B</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARALLELE__B = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Parallele</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARALLELE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.Parallele2Impl <em>Parallele2</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.Parallele2Impl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getParallele2()
   * @generated
   */
  int PARALLELE2 = 29;

  /**
   * The feature id for the '<em><b>A</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARALLELE2__A = PARALLELE__A;

  /**
   * The feature id for the '<em><b>B</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARALLELE2__B = PARALLELE__B;

  /**
   * The feature id for the '<em><b>T</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARALLELE2__T = PARALLELE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Parallele2</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARALLELE2_FEATURE_COUNT = PARALLELE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.Parallele3Impl <em>Parallele3</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.Parallele3Impl
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getParallele3()
   * @generated
   */
  int PARALLELE3 = 30;

  /**
   * The feature id for the '<em><b>A</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARALLELE3__A = PARALLELE__A;

  /**
   * The feature id for the '<em><b>B</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARALLELE3__B = PARALLELE__B;

  /**
   * The feature id for the '<em><b>C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARALLELE3__C = PARALLELE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Parallele3</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARALLELE3_FEATURE_COUNT = PARALLELE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Model#getFonctions <em>Fonctions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fonctions</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Model#getFonctions()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Fonctions();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.PourcentConst <em>Pourcent Const</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pourcent Const</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.PourcentConst
   * @generated
   */
  EClass getPourcentConst();

  /**
   * Returns the meta object for the attribute '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.PourcentConst#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.PourcentConst#getVal()
   * @see #getPourcentConst()
   * @generated
   */
  EAttribute getPourcentConst_Val();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Monter <em>Monter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Monter</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Monter
   * @generated
   */
  EClass getMonter();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Monter#getDuree <em>Duree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Duree</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Monter#getDuree()
   * @see #getMonter()
   * @generated
   */
  EReference getMonter_Duree();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Monter#getVitesse_verticale <em>Vitesse verticale</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vitesse verticale</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Monter#getVitesse_verticale()
   * @see #getMonter()
   * @generated
   */
  EReference getMonter_Vitesse_verticale();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Descendre <em>Descendre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Descendre</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Descendre
   * @generated
   */
  EClass getDescendre();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Descendre#getDuree <em>Duree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Duree</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Descendre#getDuree()
   * @see #getDescendre()
   * @generated
   */
  EReference getDescendre_Duree();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Descendre#getVitesse_verticale <em>Vitesse verticale</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vitesse verticale</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Descendre#getVitesse_verticale()
   * @see #getDescendre()
   * @generated
   */
  EReference getDescendre_Vitesse_verticale();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Avancer <em>Avancer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Avancer</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Avancer
   * @generated
   */
  EClass getAvancer();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Avancer#getDuree <em>Duree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Duree</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Avancer#getDuree()
   * @see #getAvancer()
   * @generated
   */
  EReference getAvancer_Duree();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Avancer#getVitesse_deplacement <em>Vitesse deplacement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vitesse deplacement</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Avancer#getVitesse_deplacement()
   * @see #getAvancer()
   * @generated
   */
  EReference getAvancer_Vitesse_deplacement();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Reculer <em>Reculer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reculer</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Reculer
   * @generated
   */
  EClass getReculer();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Reculer#getDuree <em>Duree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Duree</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Reculer#getDuree()
   * @see #getReculer()
   * @generated
   */
  EReference getReculer_Duree();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Reculer#getVitesse_deplacement <em>Vitesse deplacement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vitesse deplacement</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Reculer#getVitesse_deplacement()
   * @see #getReculer()
   * @generated
   */
  EReference getReculer_Vitesse_deplacement();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Gauche <em>Gauche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Gauche</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Gauche
   * @generated
   */
  EClass getGauche();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Gauche#getDuree <em>Duree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Duree</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Gauche#getDuree()
   * @see #getGauche()
   * @generated
   */
  EReference getGauche_Duree();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Gauche#getVitesse_deplacement <em>Vitesse deplacement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vitesse deplacement</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Gauche#getVitesse_deplacement()
   * @see #getGauche()
   * @generated
   */
  EReference getGauche_Vitesse_deplacement();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Droite <em>Droite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Droite</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Droite
   * @generated
   */
  EClass getDroite();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Droite#getDuree <em>Duree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Duree</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Droite#getDuree()
   * @see #getDroite()
   * @generated
   */
  EReference getDroite_Duree();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Droite#getVitesse_deplacement <em>Vitesse deplacement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vitesse deplacement</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Droite#getVitesse_deplacement()
   * @see #getDroite()
   * @generated
   */
  EReference getDroite_Vitesse_deplacement();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Pause <em>Pause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pause</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Pause
   * @generated
   */
  EClass getPause();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Pause#getDuree <em>Duree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Duree</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Pause#getDuree()
   * @see #getPause()
   * @generated
   */
  EReference getPause_Duree();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.RotationGauche <em>Rotation Gauche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotation Gauche</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.RotationGauche
   * @generated
   */
  EClass getRotationGauche();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.RotationGauche#getDuree <em>Duree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Duree</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.RotationGauche#getDuree()
   * @see #getRotationGauche()
   * @generated
   */
  EReference getRotationGauche_Duree();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.RotationGauche#getVitesse_rotation <em>Vitesse rotation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vitesse rotation</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.RotationGauche#getVitesse_rotation()
   * @see #getRotationGauche()
   * @generated
   */
  EReference getRotationGauche_Vitesse_rotation();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.RotationDroite <em>Rotation Droite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotation Droite</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.RotationDroite
   * @generated
   */
  EClass getRotationDroite();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.RotationDroite#getDuree <em>Duree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Duree</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.RotationDroite#getDuree()
   * @see #getRotationDroite()
   * @generated
   */
  EReference getRotationDroite_Duree();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.RotationDroite#getVitesse_rotation <em>Vitesse rotation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vitesse rotation</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.RotationDroite#getVitesse_rotation()
   * @see #getRotationDroite()
   * @generated
   */
  EReference getRotationDroite_Vitesse_rotation();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionDecl <em>Fonction Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fonction Decl</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionDecl
   * @generated
   */
  EClass getFonctionDecl();

  /**
   * Returns the meta object for the attribute list '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionDecl#getA <em>A</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>A</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionDecl#getA()
   * @see #getFonctionDecl()
   * @generated
   */
  EAttribute getFonctionDecl_A();

  /**
   * Returns the meta object for the attribute list '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionDecl#getB <em>B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>B</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionDecl#getB()
   * @see #getFonctionDecl()
   * @generated
   */
  EAttribute getFonctionDecl_B();

  /**
   * Returns the meta object for the containment reference list '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionDecl#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Body</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionDecl#getBody()
   * @see #getFonctionDecl()
   * @generated
   */
  EReference getFonctionDecl_Body();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionExterne <em>Fonction Externe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fonction Externe</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionExterne
   * @generated
   */
  EClass getFonctionExterne();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionCall <em>Fonction Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fonction Call</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionCall
   * @generated
   */
  EClass getFonctionCall();

  /**
   * Returns the meta object for the reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionCall#getFunc <em>Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Func</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionCall#getFunc()
   * @see #getFonctionCall()
   * @generated
   */
  EReference getFonctionCall_Func();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionRef <em>Fonction Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fonction Ref</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionRef
   * @generated
   */
  EClass getFonctionRef();

  /**
   * Returns the meta object for the attribute '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionRef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionRef#getName()
   * @see #getFonctionRef()
   * @generated
   */
  EAttribute getFonctionRef_Name();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.PourcentDecl <em>Pourcent Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pourcent Decl</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.PourcentDecl
   * @generated
   */
  EClass getPourcentDecl();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.PourcentDecl#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.PourcentDecl#getVal()
   * @see #getPourcentDecl()
   * @generated
   */
  EReference getPourcentDecl_Val();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.IntDecl <em>Int Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Decl</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.IntDecl
   * @generated
   */
  EClass getIntDecl();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.IntDecl#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.IntDecl#getVal()
   * @see #getIntDecl()
   * @generated
   */
  EReference getIntDecl_Val();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.VarDecl <em>Var Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Decl</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.VarDecl
   * @generated
   */
  EClass getVarDecl();

  /**
   * Returns the meta object for the attribute '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.VarDecl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.VarDecl#getName()
   * @see #getVarDecl()
   * @generated
   */
  EAttribute getVarDecl_Name();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.PourcentExp <em>Pourcent Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pourcent Exp</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.PourcentExp
   * @generated
   */
  EClass getPourcentExp();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.RefIntVar <em>Ref Int Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ref Int Var</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.RefIntVar
   * @generated
   */
  EClass getRefIntVar();

  /**
   * Returns the meta object for the reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.RefIntVar#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.RefIntVar#getVar()
   * @see #getRefIntVar()
   * @generated
   */
  EReference getRefIntVar_Var();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.RefPourcentVar <em>Ref Pourcent Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ref Pourcent Var</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.RefPourcentVar
   * @generated
   */
  EClass getRefPourcentVar();

  /**
   * Returns the meta object for the reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.RefPourcentVar#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.RefPourcentVar#getVar()
   * @see #getRefPourcentVar()
   * @generated
   */
  EReference getRefPourcentVar_Var();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.IntConstante <em>Int Constante</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Constante</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.IntConstante
   * @generated
   */
  EClass getIntConstante();

  /**
   * Returns the meta object for the attribute '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.IntConstante#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.IntConstante#getVal()
   * @see #getIntConstante()
   * @generated
   */
  EAttribute getIntConstante_Val();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.IntExp <em>Int Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Exp</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.IntExp
   * @generated
   */
  EClass getIntExp();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.MD <em>MD</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MD</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.MD
   * @generated
   */
  EClass getMD();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.GDr <em>GDr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GDr</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.GDr
   * @generated
   */
  EClass getGDr();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.RGRD <em>RGRD</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RGRD</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.RGRD
   * @generated
   */
  EClass getRGRD();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.AR <em>AR</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>AR</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.AR
   * @generated
   */
  EClass getAR();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele <em>Parallele</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parallele</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele
   * @generated
   */
  EClass getParallele();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele#getA <em>A</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>A</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele#getA()
   * @see #getParallele()
   * @generated
   */
  EReference getParallele_A();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele#getB <em>B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>B</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele#getB()
   * @see #getParallele()
   * @generated
   */
  EReference getParallele_B();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele2 <em>Parallele2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parallele2</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele2
   * @generated
   */
  EClass getParallele2();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele2#getT <em>T</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>T</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele2#getT()
   * @see #getParallele2()
   * @generated
   */
  EReference getParallele2_T();

  /**
   * Returns the meta object for class '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele3 <em>Parallele3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parallele3</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele3
   * @generated
   */
  EClass getParallele3();

  /**
   * Returns the meta object for the containment reference '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele3#getC <em>C</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>C</em>'.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele3#getC()
   * @see #getParallele3()
   * @generated
   */
  EReference getParallele3_C();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DroneDSLLibFactory getDroneDSLLibFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.ModelImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Fonctions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__FONCTIONS = eINSTANCE.getModel_Fonctions();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.PourcentConstImpl <em>Pourcent Const</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.PourcentConstImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getPourcentConst()
     * @generated
     */
    EClass POURCENT_CONST = eINSTANCE.getPourcentConst();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POURCENT_CONST__VAL = eINSTANCE.getPourcentConst_Val();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.MonterImpl <em>Monter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.MonterImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getMonter()
     * @generated
     */
    EClass MONTER = eINSTANCE.getMonter();

    /**
     * The meta object literal for the '<em><b>Duree</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MONTER__DUREE = eINSTANCE.getMonter_Duree();

    /**
     * The meta object literal for the '<em><b>Vitesse verticale</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MONTER__VITESSE_VERTICALE = eINSTANCE.getMonter_Vitesse_verticale();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DescendreImpl <em>Descendre</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DescendreImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getDescendre()
     * @generated
     */
    EClass DESCENDRE = eINSTANCE.getDescendre();

    /**
     * The meta object literal for the '<em><b>Duree</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESCENDRE__DUREE = eINSTANCE.getDescendre_Duree();

    /**
     * The meta object literal for the '<em><b>Vitesse verticale</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESCENDRE__VITESSE_VERTICALE = eINSTANCE.getDescendre_Vitesse_verticale();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.AvancerImpl <em>Avancer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.AvancerImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getAvancer()
     * @generated
     */
    EClass AVANCER = eINSTANCE.getAvancer();

    /**
     * The meta object literal for the '<em><b>Duree</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AVANCER__DUREE = eINSTANCE.getAvancer_Duree();

    /**
     * The meta object literal for the '<em><b>Vitesse deplacement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AVANCER__VITESSE_DEPLACEMENT = eINSTANCE.getAvancer_Vitesse_deplacement();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.ReculerImpl <em>Reculer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.ReculerImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getReculer()
     * @generated
     */
    EClass RECULER = eINSTANCE.getReculer();

    /**
     * The meta object literal for the '<em><b>Duree</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECULER__DUREE = eINSTANCE.getReculer_Duree();

    /**
     * The meta object literal for the '<em><b>Vitesse deplacement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECULER__VITESSE_DEPLACEMENT = eINSTANCE.getReculer_Vitesse_deplacement();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.GaucheImpl <em>Gauche</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.GaucheImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getGauche()
     * @generated
     */
    EClass GAUCHE = eINSTANCE.getGauche();

    /**
     * The meta object literal for the '<em><b>Duree</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAUCHE__DUREE = eINSTANCE.getGauche_Duree();

    /**
     * The meta object literal for the '<em><b>Vitesse deplacement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAUCHE__VITESSE_DEPLACEMENT = eINSTANCE.getGauche_Vitesse_deplacement();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroiteImpl <em>Droite</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroiteImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getDroite()
     * @generated
     */
    EClass DROITE = eINSTANCE.getDroite();

    /**
     * The meta object literal for the '<em><b>Duree</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DROITE__DUREE = eINSTANCE.getDroite_Duree();

    /**
     * The meta object literal for the '<em><b>Vitesse deplacement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DROITE__VITESSE_DEPLACEMENT = eINSTANCE.getDroite_Vitesse_deplacement();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.PauseImpl <em>Pause</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.PauseImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getPause()
     * @generated
     */
    EClass PAUSE = eINSTANCE.getPause();

    /**
     * The meta object literal for the '<em><b>Duree</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAUSE__DUREE = eINSTANCE.getPause_Duree();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RotationGaucheImpl <em>Rotation Gauche</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RotationGaucheImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getRotationGauche()
     * @generated
     */
    EClass ROTATION_GAUCHE = eINSTANCE.getRotationGauche();

    /**
     * The meta object literal for the '<em><b>Duree</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROTATION_GAUCHE__DUREE = eINSTANCE.getRotationGauche_Duree();

    /**
     * The meta object literal for the '<em><b>Vitesse rotation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROTATION_GAUCHE__VITESSE_ROTATION = eINSTANCE.getRotationGauche_Vitesse_rotation();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RotationDroiteImpl <em>Rotation Droite</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RotationDroiteImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getRotationDroite()
     * @generated
     */
    EClass ROTATION_DROITE = eINSTANCE.getRotationDroite();

    /**
     * The meta object literal for the '<em><b>Duree</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROTATION_DROITE__DUREE = eINSTANCE.getRotationDroite_Duree();

    /**
     * The meta object literal for the '<em><b>Vitesse rotation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROTATION_DROITE__VITESSE_ROTATION = eINSTANCE.getRotationDroite_Vitesse_rotation();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.StatementImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.FonctionDeclImpl <em>Fonction Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.FonctionDeclImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getFonctionDecl()
     * @generated
     */
    EClass FONCTION_DECL = eINSTANCE.getFonctionDecl();

    /**
     * The meta object literal for the '<em><b>A</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FONCTION_DECL__A = eINSTANCE.getFonctionDecl_A();

    /**
     * The meta object literal for the '<em><b>B</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FONCTION_DECL__B = eINSTANCE.getFonctionDecl_B();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FONCTION_DECL__BODY = eINSTANCE.getFonctionDecl_Body();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.FonctionExterneImpl <em>Fonction Externe</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.FonctionExterneImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getFonctionExterne()
     * @generated
     */
    EClass FONCTION_EXTERNE = eINSTANCE.getFonctionExterne();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.FonctionCallImpl <em>Fonction Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.FonctionCallImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getFonctionCall()
     * @generated
     */
    EClass FONCTION_CALL = eINSTANCE.getFonctionCall();

    /**
     * The meta object literal for the '<em><b>Func</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FONCTION_CALL__FUNC = eINSTANCE.getFonctionCall_Func();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.FonctionRefImpl <em>Fonction Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.FonctionRefImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getFonctionRef()
     * @generated
     */
    EClass FONCTION_REF = eINSTANCE.getFonctionRef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FONCTION_REF__NAME = eINSTANCE.getFonctionRef_Name();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.PourcentDeclImpl <em>Pourcent Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.PourcentDeclImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getPourcentDecl()
     * @generated
     */
    EClass POURCENT_DECL = eINSTANCE.getPourcentDecl();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POURCENT_DECL__VAL = eINSTANCE.getPourcentDecl_Val();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.IntDeclImpl <em>Int Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.IntDeclImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getIntDecl()
     * @generated
     */
    EClass INT_DECL = eINSTANCE.getIntDecl();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INT_DECL__VAL = eINSTANCE.getIntDecl_Val();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.VarDeclImpl <em>Var Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.VarDeclImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getVarDecl()
     * @generated
     */
    EClass VAR_DECL = eINSTANCE.getVarDecl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR_DECL__NAME = eINSTANCE.getVarDecl_Name();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.PourcentExpImpl <em>Pourcent Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.PourcentExpImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getPourcentExp()
     * @generated
     */
    EClass POURCENT_EXP = eINSTANCE.getPourcentExp();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RefIntVarImpl <em>Ref Int Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RefIntVarImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getRefIntVar()
     * @generated
     */
    EClass REF_INT_VAR = eINSTANCE.getRefIntVar();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REF_INT_VAR__VAR = eINSTANCE.getRefIntVar_Var();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RefPourcentVarImpl <em>Ref Pourcent Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RefPourcentVarImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getRefPourcentVar()
     * @generated
     */
    EClass REF_POURCENT_VAR = eINSTANCE.getRefPourcentVar();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REF_POURCENT_VAR__VAR = eINSTANCE.getRefPourcentVar_Var();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.IntConstanteImpl <em>Int Constante</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.IntConstanteImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getIntConstante()
     * @generated
     */
    EClass INT_CONSTANTE = eINSTANCE.getIntConstante();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_CONSTANTE__VAL = eINSTANCE.getIntConstante_Val();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.IntExpImpl <em>Int Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.IntExpImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getIntExp()
     * @generated
     */
    EClass INT_EXP = eINSTANCE.getIntExp();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.MDImpl <em>MD</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.MDImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getMD()
     * @generated
     */
    EClass MD = eINSTANCE.getMD();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.GDrImpl <em>GDr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.GDrImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getGDr()
     * @generated
     */
    EClass GDR = eINSTANCE.getGDr();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RGRDImpl <em>RGRD</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.RGRDImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getRGRD()
     * @generated
     */
    EClass RGRD = eINSTANCE.getRGRD();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.ARImpl <em>AR</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.ARImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getAR()
     * @generated
     */
    EClass AR = eINSTANCE.getAR();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.ParalleleImpl <em>Parallele</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.ParalleleImpl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getParallele()
     * @generated
     */
    EClass PARALLELE = eINSTANCE.getParallele();

    /**
     * The meta object literal for the '<em><b>A</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARALLELE__A = eINSTANCE.getParallele_A();

    /**
     * The meta object literal for the '<em><b>B</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARALLELE__B = eINSTANCE.getParallele_B();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.Parallele2Impl <em>Parallele2</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.Parallele2Impl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getParallele2()
     * @generated
     */
    EClass PARALLELE2 = eINSTANCE.getParallele2();

    /**
     * The meta object literal for the '<em><b>T</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARALLELE2__T = eINSTANCE.getParallele2_T();

    /**
     * The meta object literal for the '{@link fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.Parallele3Impl <em>Parallele3</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.Parallele3Impl
     * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl.DroneDSLLibPackageImpl#getParallele3()
     * @generated
     */
    EClass PARALLELE3 = eINSTANCE.getParallele3();

    /**
     * The meta object literal for the '<em><b>C</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARALLELE3__C = eINSTANCE.getParallele3_C();

  }

} //DroneDSLLibPackage
