/**
 * generated by Xtext 2.12.0
 */
package fr.idmteam1.idmproject.dronedsl.droneDSLLib;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Seconde Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.DroneDSLLibPackage#getSecondeExp()
 * @model
 * @generated
 */
public interface SecondeExp extends EObject
{
} // SecondeExp
