/**
 * generated by Xtext 2.12.0
 */
package fr.idmteam1.idmproject.dronedsl.ui.contentassist;

import fr.idmteam1.idmproject.dronedsl.ui.contentassist.AbstractDroneDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DroneDSLProposalProvider extends AbstractDroneDSLProposalProvider {
}
