/**
 * generated by Xtext 2.12.0
 */
package fr.idmteam1.idmproject.dronedsl.droneDSLLib.impl;

import fr.idmteam1.idmproject.dronedsl.droneDSLLib.Atterrir;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.Avancer;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.CommandeBasique;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.Decoller;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.DecollerAtterrir;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.Descendre;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.Droite;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.DroneDSLLibFactory;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.DroneDSLLibPackage;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionCall;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionCallInterne;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.FonctionDecl;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.GDr;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.Gauche;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.Model;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.Monter;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.Mouvement;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele2;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele3;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.Parallele4;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.Pause;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.PourcentConst;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.PourcentDecl;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.PourcentExp;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.Reculer;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.RefPourcentVar;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.RefSecondeVar;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.RotationDroite;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.RotationGauche;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.SecondeConst;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.SecondeDecl;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.SecondeExp;
import fr.idmteam1.idmproject.dronedsl.droneDSLLib.VarDecl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class DroneDSLLibPackageImpl extends EPackageImpl implements DroneDSLLibPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass secondeConstEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass pourcentConstEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass secondeDeclEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass pourcentDeclEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass varDeclEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass refSecondeVarEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass refPourcentVarEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass pourcentExpEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass secondeExpEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass decollerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass atterrirEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass monterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass descendreEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass avancerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass reculerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass gaucheEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass droiteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass rotationGaucheEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass rotationDroiteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass pauseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mouvementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass decollerAtterrirEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass commandeBasiqueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fonctionDeclEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fonctionCallEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fonctionCallInterneEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mdEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass gDrEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass rgrdEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass arEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass paralleleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass parallele2EClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass parallele3EClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass parallele4EClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see fr.idmteam1.idmproject.dronedsl.droneDSLLib.DroneDSLLibPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private DroneDSLLibPackageImpl()
  {
    super(eNS_URI, DroneDSLLibFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link DroneDSLLibPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static DroneDSLLibPackage init()
  {
    if (isInited) return (DroneDSLLibPackage)EPackage.Registry.INSTANCE.getEPackage(DroneDSLLibPackage.eNS_URI);

    // Obtain or create and register package
    DroneDSLLibPackageImpl theDroneDSLLibPackage = (DroneDSLLibPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof DroneDSLLibPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new DroneDSLLibPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theDroneDSLLibPackage.createPackageContents();

    // Initialize created meta-data
    theDroneDSLLibPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theDroneDSLLibPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(DroneDSLLibPackage.eNS_URI, theDroneDSLLibPackage);
    return theDroneDSLLibPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModel_Fonctions()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSecondeConst()
  {
    return secondeConstEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSecondeConst_Val()
  {
    return (EAttribute)secondeConstEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPourcentConst()
  {
    return pourcentConstEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPourcentConst_Val()
  {
    return (EAttribute)pourcentConstEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSecondeDecl()
  {
    return secondeDeclEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSecondeDecl_Val()
  {
    return (EReference)secondeDeclEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPourcentDecl()
  {
    return pourcentDeclEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPourcentDecl_Val()
  {
    return (EReference)pourcentDeclEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getVarDecl()
  {
    return varDeclEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getVarDecl_Name()
  {
    return (EAttribute)varDeclEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRefSecondeVar()
  {
    return refSecondeVarEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRefSecondeVar_Var()
  {
    return (EReference)refSecondeVarEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRefPourcentVar()
  {
    return refPourcentVarEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRefPourcentVar_Var()
  {
    return (EReference)refPourcentVarEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPourcentExp()
  {
    return pourcentExpEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSecondeExp()
  {
    return secondeExpEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDecoller()
  {
    return decollerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAtterrir()
  {
    return atterrirEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMonter()
  {
    return monterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMonter_Duree()
  {
    return (EReference)monterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMonter_Vitesse()
  {
    return (EReference)monterEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDescendre()
  {
    return descendreEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDescendre_Duree()
  {
    return (EReference)descendreEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDescendre_Vitesse()
  {
    return (EReference)descendreEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAvancer()
  {
    return avancerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAvancer_Duree()
  {
    return (EReference)avancerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAvancer_Vitesse()
  {
    return (EReference)avancerEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getReculer()
  {
    return reculerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getReculer_Duree()
  {
    return (EReference)reculerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getReculer_Vitesse()
  {
    return (EReference)reculerEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getGauche()
  {
    return gaucheEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getGauche_Duree()
  {
    return (EReference)gaucheEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getGauche_Vitesse()
  {
    return (EReference)gaucheEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDroite()
  {
    return droiteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDroite_Duree()
  {
    return (EReference)droiteEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDroite_Vitesse()
  {
    return (EReference)droiteEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRotationGauche()
  {
    return rotationGaucheEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRotationGauche_Duree()
  {
    return (EReference)rotationGaucheEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRotationGauche_Vitesse()
  {
    return (EReference)rotationGaucheEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRotationDroite()
  {
    return rotationDroiteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRotationDroite_Duree()
  {
    return (EReference)rotationDroiteEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRotationDroite_Vitesse()
  {
    return (EReference)rotationDroiteEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPause()
  {
    return pauseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPause_Duree()
  {
    return (EReference)pauseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMouvement()
  {
    return mouvementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDecollerAtterrir()
  {
    return decollerAtterrirEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDecollerAtterrir_Str()
  {
    return (EAttribute)decollerAtterrirEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCommandeBasique()
  {
    return commandeBasiqueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFonctionDecl()
  {
    return fonctionDeclEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFonctionDecl_Name()
  {
    return (EAttribute)fonctionDeclEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFonctionDecl_Body()
  {
    return (EReference)fonctionDeclEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFonctionCall()
  {
    return fonctionCallEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFonctionCallInterne()
  {
    return fonctionCallInterneEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getFonctionCallInterne_Ref()
  {
    return (EReference)fonctionCallInterneEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMD()
  {
    return mdEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getGDr()
  {
    return gDrEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRGRD()
  {
    return rgrdEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAR()
  {
    return arEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getParallele()
  {
    return paralleleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getParallele_A()
  {
    return (EReference)paralleleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getParallele_B()
  {
    return (EReference)paralleleEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getParallele2()
  {
    return parallele2EClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getParallele2_T()
  {
    return (EReference)parallele2EClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getParallele3()
  {
    return parallele3EClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getParallele3_C()
  {
    return (EReference)parallele3EClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getParallele4()
  {
    return parallele4EClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getParallele4_C()
  {
    return (EReference)parallele4EClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getParallele4_D()
  {
    return (EReference)parallele4EClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DroneDSLLibFactory getDroneDSLLibFactory()
  {
    return (DroneDSLLibFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__FONCTIONS);

    secondeConstEClass = createEClass(SECONDE_CONST);
    createEAttribute(secondeConstEClass, SECONDE_CONST__VAL);

    pourcentConstEClass = createEClass(POURCENT_CONST);
    createEAttribute(pourcentConstEClass, POURCENT_CONST__VAL);

    secondeDeclEClass = createEClass(SECONDE_DECL);
    createEReference(secondeDeclEClass, SECONDE_DECL__VAL);

    pourcentDeclEClass = createEClass(POURCENT_DECL);
    createEReference(pourcentDeclEClass, POURCENT_DECL__VAL);

    varDeclEClass = createEClass(VAR_DECL);
    createEAttribute(varDeclEClass, VAR_DECL__NAME);

    refSecondeVarEClass = createEClass(REF_SECONDE_VAR);
    createEReference(refSecondeVarEClass, REF_SECONDE_VAR__VAR);

    refPourcentVarEClass = createEClass(REF_POURCENT_VAR);
    createEReference(refPourcentVarEClass, REF_POURCENT_VAR__VAR);

    pourcentExpEClass = createEClass(POURCENT_EXP);

    secondeExpEClass = createEClass(SECONDE_EXP);

    decollerEClass = createEClass(DECOLLER);

    atterrirEClass = createEClass(ATTERRIR);

    monterEClass = createEClass(MONTER);
    createEReference(monterEClass, MONTER__DUREE);
    createEReference(monterEClass, MONTER__VITESSE);

    descendreEClass = createEClass(DESCENDRE);
    createEReference(descendreEClass, DESCENDRE__DUREE);
    createEReference(descendreEClass, DESCENDRE__VITESSE);

    avancerEClass = createEClass(AVANCER);
    createEReference(avancerEClass, AVANCER__DUREE);
    createEReference(avancerEClass, AVANCER__VITESSE);

    reculerEClass = createEClass(RECULER);
    createEReference(reculerEClass, RECULER__DUREE);
    createEReference(reculerEClass, RECULER__VITESSE);

    gaucheEClass = createEClass(GAUCHE);
    createEReference(gaucheEClass, GAUCHE__DUREE);
    createEReference(gaucheEClass, GAUCHE__VITESSE);

    droiteEClass = createEClass(DROITE);
    createEReference(droiteEClass, DROITE__DUREE);
    createEReference(droiteEClass, DROITE__VITESSE);

    rotationGaucheEClass = createEClass(ROTATION_GAUCHE);
    createEReference(rotationGaucheEClass, ROTATION_GAUCHE__DUREE);
    createEReference(rotationGaucheEClass, ROTATION_GAUCHE__VITESSE);

    rotationDroiteEClass = createEClass(ROTATION_DROITE);
    createEReference(rotationDroiteEClass, ROTATION_DROITE__DUREE);
    createEReference(rotationDroiteEClass, ROTATION_DROITE__VITESSE);

    pauseEClass = createEClass(PAUSE);
    createEReference(pauseEClass, PAUSE__DUREE);

    mouvementEClass = createEClass(MOUVEMENT);

    decollerAtterrirEClass = createEClass(DECOLLER_ATTERRIR);
    createEAttribute(decollerAtterrirEClass, DECOLLER_ATTERRIR__STR);

    commandeBasiqueEClass = createEClass(COMMANDE_BASIQUE);

    fonctionDeclEClass = createEClass(FONCTION_DECL);
    createEAttribute(fonctionDeclEClass, FONCTION_DECL__NAME);
    createEReference(fonctionDeclEClass, FONCTION_DECL__BODY);

    fonctionCallEClass = createEClass(FONCTION_CALL);

    fonctionCallInterneEClass = createEClass(FONCTION_CALL_INTERNE);
    createEReference(fonctionCallInterneEClass, FONCTION_CALL_INTERNE__REF);

    mdEClass = createEClass(MD);

    gDrEClass = createEClass(GDR);

    rgrdEClass = createEClass(RGRD);

    arEClass = createEClass(AR);

    paralleleEClass = createEClass(PARALLELE);
    createEReference(paralleleEClass, PARALLELE__A);
    createEReference(paralleleEClass, PARALLELE__B);

    parallele2EClass = createEClass(PARALLELE2);
    createEReference(parallele2EClass, PARALLELE2__T);

    parallele3EClass = createEClass(PARALLELE3);
    createEReference(parallele3EClass, PARALLELE3__C);

    parallele4EClass = createEClass(PARALLELE4);
    createEReference(parallele4EClass, PARALLELE4__C);
    createEReference(parallele4EClass, PARALLELE4__D);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    secondeConstEClass.getESuperTypes().add(this.getSecondeExp());
    pourcentConstEClass.getESuperTypes().add(this.getPourcentExp());
    secondeDeclEClass.getESuperTypes().add(this.getVarDecl());
    pourcentDeclEClass.getESuperTypes().add(this.getVarDecl());
    refSecondeVarEClass.getESuperTypes().add(this.getSecondeExp());
    refPourcentVarEClass.getESuperTypes().add(this.getPourcentExp());
    decollerEClass.getESuperTypes().add(this.getDecollerAtterrir());
    atterrirEClass.getESuperTypes().add(this.getDecollerAtterrir());
    monterEClass.getESuperTypes().add(this.getMouvement());
    monterEClass.getESuperTypes().add(this.getCommandeBasique());
    monterEClass.getESuperTypes().add(this.getMD());
    descendreEClass.getESuperTypes().add(this.getMouvement());
    descendreEClass.getESuperTypes().add(this.getCommandeBasique());
    descendreEClass.getESuperTypes().add(this.getMD());
    avancerEClass.getESuperTypes().add(this.getMouvement());
    avancerEClass.getESuperTypes().add(this.getCommandeBasique());
    avancerEClass.getESuperTypes().add(this.getAR());
    reculerEClass.getESuperTypes().add(this.getMouvement());
    reculerEClass.getESuperTypes().add(this.getCommandeBasique());
    reculerEClass.getESuperTypes().add(this.getAR());
    gaucheEClass.getESuperTypes().add(this.getMouvement());
    gaucheEClass.getESuperTypes().add(this.getCommandeBasique());
    gaucheEClass.getESuperTypes().add(this.getGDr());
    droiteEClass.getESuperTypes().add(this.getMouvement());
    droiteEClass.getESuperTypes().add(this.getCommandeBasique());
    droiteEClass.getESuperTypes().add(this.getGDr());
    rotationGaucheEClass.getESuperTypes().add(this.getMouvement());
    rotationGaucheEClass.getESuperTypes().add(this.getCommandeBasique());
    rotationGaucheEClass.getESuperTypes().add(this.getRGRD());
    rotationDroiteEClass.getESuperTypes().add(this.getMouvement());
    rotationDroiteEClass.getESuperTypes().add(this.getCommandeBasique());
    rotationDroiteEClass.getESuperTypes().add(this.getRGRD());
    pauseEClass.getESuperTypes().add(this.getCommandeBasique());
    fonctionCallInterneEClass.getESuperTypes().add(this.getFonctionCall());
    paralleleEClass.getESuperTypes().add(this.getMouvement());
    parallele2EClass.getESuperTypes().add(this.getParallele());
    parallele3EClass.getESuperTypes().add(this.getParallele());
    parallele4EClass.getESuperTypes().add(this.getParallele());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Fonctions(), this.getFonctionDecl(), null, "fonctions", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(secondeConstEClass, SecondeConst.class, "SecondeConst", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSecondeConst_Val(), ecorePackage.getEString(), "val", null, 0, 1, SecondeConst.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(pourcentConstEClass, PourcentConst.class, "PourcentConst", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPourcentConst_Val(), ecorePackage.getEString(), "val", null, 0, 1, PourcentConst.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(secondeDeclEClass, SecondeDecl.class, "SecondeDecl", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSecondeDecl_Val(), this.getSecondeConst(), null, "val", null, 0, 1, SecondeDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(pourcentDeclEClass, PourcentDecl.class, "PourcentDecl", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPourcentDecl_Val(), this.getPourcentConst(), null, "val", null, 0, 1, PourcentDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(varDeclEClass, VarDecl.class, "VarDecl", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVarDecl_Name(), ecorePackage.getEString(), "name", null, 0, 1, VarDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(refSecondeVarEClass, RefSecondeVar.class, "RefSecondeVar", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRefSecondeVar_Var(), this.getSecondeDecl(), null, "var", null, 0, 1, RefSecondeVar.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(refPourcentVarEClass, RefPourcentVar.class, "RefPourcentVar", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRefPourcentVar_Var(), this.getPourcentDecl(), null, "var", null, 0, 1, RefPourcentVar.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(pourcentExpEClass, PourcentExp.class, "PourcentExp", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(secondeExpEClass, SecondeExp.class, "SecondeExp", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(decollerEClass, Decoller.class, "Decoller", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(atterrirEClass, Atterrir.class, "Atterrir", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(monterEClass, Monter.class, "Monter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMonter_Duree(), this.getSecondeExp(), null, "duree", null, 0, 1, Monter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMonter_Vitesse(), this.getPourcentExp(), null, "vitesse", null, 0, 1, Monter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(descendreEClass, Descendre.class, "Descendre", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDescendre_Duree(), this.getSecondeExp(), null, "duree", null, 0, 1, Descendre.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDescendre_Vitesse(), this.getPourcentExp(), null, "vitesse", null, 0, 1, Descendre.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(avancerEClass, Avancer.class, "Avancer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAvancer_Duree(), this.getSecondeExp(), null, "duree", null, 0, 1, Avancer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAvancer_Vitesse(), this.getPourcentExp(), null, "vitesse", null, 0, 1, Avancer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(reculerEClass, Reculer.class, "Reculer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getReculer_Duree(), this.getSecondeExp(), null, "duree", null, 0, 1, Reculer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getReculer_Vitesse(), this.getPourcentExp(), null, "vitesse", null, 0, 1, Reculer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(gaucheEClass, Gauche.class, "Gauche", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getGauche_Duree(), this.getSecondeExp(), null, "duree", null, 0, 1, Gauche.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGauche_Vitesse(), this.getPourcentExp(), null, "vitesse", null, 0, 1, Gauche.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(droiteEClass, Droite.class, "Droite", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDroite_Duree(), this.getSecondeExp(), null, "duree", null, 0, 1, Droite.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDroite_Vitesse(), this.getPourcentExp(), null, "vitesse", null, 0, 1, Droite.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(rotationGaucheEClass, RotationGauche.class, "RotationGauche", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRotationGauche_Duree(), this.getSecondeExp(), null, "duree", null, 0, 1, RotationGauche.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRotationGauche_Vitesse(), this.getPourcentExp(), null, "vitesse", null, 0, 1, RotationGauche.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(rotationDroiteEClass, RotationDroite.class, "RotationDroite", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRotationDroite_Duree(), this.getSecondeExp(), null, "duree", null, 0, 1, RotationDroite.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRotationDroite_Vitesse(), this.getPourcentExp(), null, "vitesse", null, 0, 1, RotationDroite.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(pauseEClass, Pause.class, "Pause", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPause_Duree(), this.getSecondeExp(), null, "duree", null, 0, 1, Pause.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(mouvementEClass, Mouvement.class, "Mouvement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(decollerAtterrirEClass, DecollerAtterrir.class, "DecollerAtterrir", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDecollerAtterrir_Str(), ecorePackage.getEString(), "str", null, 0, 1, DecollerAtterrir.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(commandeBasiqueEClass, CommandeBasique.class, "CommandeBasique", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(fonctionDeclEClass, FonctionDecl.class, "FonctionDecl", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFonctionDecl_Name(), ecorePackage.getEString(), "name", null, 0, 1, FonctionDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFonctionDecl_Body(), ecorePackage.getEObject(), null, "body", null, 0, -1, FonctionDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fonctionCallEClass, FonctionCall.class, "FonctionCall", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(fonctionCallInterneEClass, FonctionCallInterne.class, "FonctionCallInterne", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFonctionCallInterne_Ref(), this.getFonctionDecl(), null, "ref", null, 0, 1, FonctionCallInterne.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(mdEClass, fr.idmteam1.idmproject.dronedsl.droneDSLLib.MD.class, "MD", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(gDrEClass, GDr.class, "GDr", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(rgrdEClass, fr.idmteam1.idmproject.dronedsl.droneDSLLib.RGRD.class, "RGRD", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(arEClass, fr.idmteam1.idmproject.dronedsl.droneDSLLib.AR.class, "AR", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(paralleleEClass, Parallele.class, "Parallele", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getParallele_A(), ecorePackage.getEObject(), null, "a", null, 0, 1, Parallele.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getParallele_B(), ecorePackage.getEObject(), null, "b", null, 0, 1, Parallele.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(parallele2EClass, Parallele2.class, "Parallele2", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getParallele2_T(), ecorePackage.getEObject(), null, "t", null, 0, 1, Parallele2.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(parallele3EClass, Parallele3.class, "Parallele3", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getParallele3_C(), ecorePackage.getEObject(), null, "c", null, 0, 1, Parallele3.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(parallele4EClass, Parallele4.class, "Parallele4", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getParallele4_C(), ecorePackage.getEObject(), null, "c", null, 0, 1, Parallele4.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getParallele4_D(), ecorePackage.getEObject(), null, "d", null, 0, 1, Parallele4.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //DroneDSLLibPackageImpl
