/*
 * generated by Xtext 2.12.0
 */
package org.roboticiens.idmProject.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.roboticiens.idmProject.ui.internal.IdmProjectActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DroneMainExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return IdmProjectActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return IdmProjectActivator.getInstance().getInjector(IdmProjectActivator.ORG_ROBOTICIENS_IDMPROJECT_DRONEMAIN);
	}
	
}
