/**
 * generated by Xtext 2.12.0
 */
package fr.idmteam1.idmproject.dronedsl.droneDSL.impl;

import fr.idmteam1.idmproject.dronedsl.droneDSL.Atterrir;
import fr.idmteam1.idmproject.dronedsl.droneDSL.DroneDSLPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Atterrir</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AtterrirImpl extends DecollerAtterrirImpl implements Atterrir
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtterrirImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DroneDSLPackage.Literals.ATTERRIR;
  }

} //AtterrirImpl
