/**
 * generated by Xtext 2.12.0
 */
package fr.idmteam1.idmproject.dronedsl.droneDSL.impl;

import fr.idmteam1.idmproject.dronedsl.droneDSL.DroneDSLPackage;
import fr.idmteam1.idmproject.dronedsl.droneDSL.Eloignement_max;
import fr.idmteam1.idmproject.dronedsl.droneDSL.SecondeConst;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Eloignement max</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.idmteam1.idmproject.dronedsl.droneDSL.impl.Eloignement_maxImpl#getEloignement_max <em>Eloignement max</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Eloignement_maxImpl extends MinimalEObjectImpl.Container implements Eloignement_max
{
  /**
   * The cached value of the '{@link #getEloignement_max() <em>Eloignement max</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEloignement_max()
   * @generated
   * @ordered
   */
  protected SecondeConst eloignement_max;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Eloignement_maxImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DroneDSLPackage.Literals.ELOIGNEMENT_MAX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SecondeConst getEloignement_max()
  {
    return eloignement_max;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEloignement_max(SecondeConst newEloignement_max, NotificationChain msgs)
  {
    SecondeConst oldEloignement_max = eloignement_max;
    eloignement_max = newEloignement_max;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DroneDSLPackage.ELOIGNEMENT_MAX__ELOIGNEMENT_MAX, oldEloignement_max, newEloignement_max);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEloignement_max(SecondeConst newEloignement_max)
  {
    if (newEloignement_max != eloignement_max)
    {
      NotificationChain msgs = null;
      if (eloignement_max != null)
        msgs = ((InternalEObject)eloignement_max).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DroneDSLPackage.ELOIGNEMENT_MAX__ELOIGNEMENT_MAX, null, msgs);
      if (newEloignement_max != null)
        msgs = ((InternalEObject)newEloignement_max).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DroneDSLPackage.ELOIGNEMENT_MAX__ELOIGNEMENT_MAX, null, msgs);
      msgs = basicSetEloignement_max(newEloignement_max, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DroneDSLPackage.ELOIGNEMENT_MAX__ELOIGNEMENT_MAX, newEloignement_max, newEloignement_max));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DroneDSLPackage.ELOIGNEMENT_MAX__ELOIGNEMENT_MAX:
        return basicSetEloignement_max(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DroneDSLPackage.ELOIGNEMENT_MAX__ELOIGNEMENT_MAX:
        return getEloignement_max();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DroneDSLPackage.ELOIGNEMENT_MAX__ELOIGNEMENT_MAX:
        setEloignement_max((SecondeConst)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DroneDSLPackage.ELOIGNEMENT_MAX__ELOIGNEMENT_MAX:
        setEloignement_max((SecondeConst)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DroneDSLPackage.ELOIGNEMENT_MAX__ELOIGNEMENT_MAX:
        return eloignement_max != null;
    }
    return super.eIsSet(featureID);
  }
  @Override
  public String toString() {
      return this.eloignement_max.getVal();
  }

} //ModifiedEloignement_maxImpl toString added
