/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myTurtleDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parallele2</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myTurtleDsl.Parallele2#getA <em>A</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myTurtleDsl.Parallele2#getT <em>T</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myTurtleDsl.Parallele2#getB <em>B</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myTurtleDsl.MyTurtleDslPackage#getParallele2()
 * @model
 * @generated
 */
public interface Parallele2 extends EObject
{
  /**
   * Returns the value of the '<em><b>A</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>A</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>A</em>' containment reference.
   * @see #setA(EObject)
   * @see org.xtext.example.mydsl.myTurtleDsl.MyTurtleDslPackage#getParallele2_A()
   * @model containment="true"
   * @generated
   */
  EObject getA();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myTurtleDsl.Parallele2#getA <em>A</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>A</em>' containment reference.
   * @see #getA()
   * @generated
   */
  void setA(EObject value);

  /**
   * Returns the value of the '<em><b>T</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>T</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>T</em>' containment reference.
   * @see #setT(EObject)
   * @see org.xtext.example.mydsl.myTurtleDsl.MyTurtleDslPackage#getParallele2_T()
   * @model containment="true"
   * @generated
   */
  EObject getT();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myTurtleDsl.Parallele2#getT <em>T</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>T</em>' containment reference.
   * @see #getT()
   * @generated
   */
  void setT(EObject value);

  /**
   * Returns the value of the '<em><b>B</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>B</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>B</em>' containment reference.
   * @see #setB(EObject)
   * @see org.xtext.example.mydsl.myTurtleDsl.MyTurtleDslPackage#getParallele2_B()
   * @model containment="true"
   * @generated
   */
  EObject getB();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myTurtleDsl.Parallele2#getB <em>B</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>B</em>' containment reference.
   * @see #getB()
   * @generated
   */
  void setB(EObject value);

} // Parallele2
