/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idm_project.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.idm_project.Idm_projectPackage;
import org.xtext.example.mydsl.idm_project.MD;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>MD</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MDImpl extends MinimalEObjectImpl.Container implements MD
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MDImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Idm_projectPackage.Literals.MD;
  }

} //MDImpl
