/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.MyTurtleDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyTurtleDslStandaloneSetup extends MyTurtleDslStandaloneSetupGenerated {
  public static void doSetup() {
    new MyTurtleDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
