/**
 * generated by Xtext 2.12.0
 */
package org.roboticiens.idmProject.droneMain;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RGRD</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.roboticiens.idmProject.droneMain.DroneMainPackage#getRGRD()
 * @model
 * @generated
 */
public interface RGRD extends EObject
{
} // RGRD
