/**
 * generated by Xtext 2.12.0
 */
package fr.idmteam1.idmproject.dronedsl.ide;

import fr.idmteam1.idmproject.dronedsl.ide.AbstractDroneDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DroneDSLIdeModule extends AbstractDroneDSLIdeModule {
}
