/**
 * generated by Xtext 2.12.0
 */
package fr.idmteam1.idmproject.dronedsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.idmteam1.idmproject.dronedsl.DroneDSLLibRuntimeModule;
import fr.idmteam1.idmproject.dronedsl.DroneDSLLibStandaloneSetup;
import fr.idmteam1.idmproject.dronedsl.ide.DroneDSLLibIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DroneDSLLibIdeSetup extends DroneDSLLibStandaloneSetup {
  @Override
  public Injector createInjector() {
    DroneDSLLibRuntimeModule _droneDSLLibRuntimeModule = new DroneDSLLibRuntimeModule();
    DroneDSLLibIdeModule _droneDSLLibIdeModule = new DroneDSLLibIdeModule();
    return Guice.createInjector(Modules2.mixin(_droneDSLLibRuntimeModule, _droneDSLLibIdeModule));
  }
}
