/**
 * generated by Xtext 2.12.0
 */
package fr.idmteam1.idmproject.dronedsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.idmteam1.idmproject.dronedsl.DroneDSLRuntimeModule;
import fr.idmteam1.idmproject.dronedsl.DroneDSLStandaloneSetup;
import fr.idmteam1.idmproject.dronedsl.ide.DroneDSLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DroneDSLIdeSetup extends DroneDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    DroneDSLRuntimeModule _droneDSLRuntimeModule = new DroneDSLRuntimeModule();
    DroneDSLIdeModule _droneDSLIdeModule = new DroneDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_droneDSLRuntimeModule, _droneDSLIdeModule));
  }
}
