/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myTurtleDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myTurtleDsl.MyTurtleDslPackage;
import org.xtext.example.mydsl.myTurtleDsl.PourcentExp;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pourcent Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PourcentExpImpl extends MinimalEObjectImpl.Container implements PourcentExp
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PourcentExpImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyTurtleDslPackage.Literals.POURCENT_EXP;
  }

} //PourcentExpImpl
