/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idm_project;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Descendre</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.idm_project.Descendre#getDuree <em>Duree</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.idm_project.Descendre#getVitesse_verticale <em>Vitesse verticale</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.idm_project.Idm_projectPackage#getDescendre()
 * @model
 * @generated
 */
public interface Descendre extends Statement, MD
{
  /**
   * Returns the value of the '<em><b>Duree</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Duree</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duree</em>' containment reference.
   * @see #setDuree(IntExp)
   * @see org.xtext.example.mydsl.idm_project.Idm_projectPackage#getDescendre_Duree()
   * @model containment="true"
   * @generated
   */
  IntExp getDuree();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idm_project.Descendre#getDuree <em>Duree</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duree</em>' containment reference.
   * @see #getDuree()
   * @generated
   */
  void setDuree(IntExp value);

  /**
   * Returns the value of the '<em><b>Vitesse verticale</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Vitesse verticale</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vitesse verticale</em>' containment reference.
   * @see #setVitesse_verticale(PourcentExp)
   * @see org.xtext.example.mydsl.idm_project.Idm_projectPackage#getDescendre_Vitesse_verticale()
   * @model containment="true"
   * @generated
   */
  PourcentExp getVitesse_verticale();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idm_project.Descendre#getVitesse_verticale <em>Vitesse verticale</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vitesse verticale</em>' containment reference.
   * @see #getVitesse_verticale()
   * @generated
   */
  void setVitesse_verticale(PourcentExp value);

} // Descendre
