/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idm_project;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pourcent vitesse deplacement max</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.idm_project.Pourcent_vitesse_deplacement_max#getVitesse_deplacement <em>Vitesse deplacement</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.idm_project.Idm_projectPackage#getPourcent_vitesse_deplacement_max()
 * @model
 * @generated
 */
public interface Pourcent_vitesse_deplacement_max extends EObject
{
  /**
   * Returns the value of the '<em><b>Vitesse deplacement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Vitesse deplacement</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vitesse deplacement</em>' containment reference.
   * @see #setVitesse_deplacement(PourcentConst)
   * @see org.xtext.example.mydsl.idm_project.Idm_projectPackage#getPourcent_vitesse_deplacement_max_Vitesse_deplacement()
   * @model containment="true"
   * @generated
   */
  PourcentConst getVitesse_deplacement();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idm_project.Pourcent_vitesse_deplacement_max#getVitesse_deplacement <em>Vitesse deplacement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vitesse deplacement</em>' containment reference.
   * @see #getVitesse_deplacement()
   * @generated
   */
  void setVitesse_deplacement(PourcentConst value);

} // Pourcent_vitesse_deplacement_max
