/**
 * generated by Xtext 2.12.0
 */
package fr.idmteam1.idmproject.dronedsl.droneDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see fr.idmteam1.idmproject.dronedsl.droneDSL.DroneDSLPackage
 * @generated
 */
public interface DroneDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DroneDSLFactory eINSTANCE = fr.idmteam1.idmproject.dronedsl.droneDSL.impl.DroneDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Main</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Main</em>'.
   * @generated
   */
  Main createMain();

  /**
   * Returns a new object of class '<em>Pourcent Const</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pourcent Const</em>'.
   * @generated
   */
  PourcentConst createPourcentConst();

  /**
   * Returns a new object of class '<em>Imports</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Imports</em>'.
   * @generated
   */
  Imports createImports();

  /**
   * Returns a new object of class '<em>Import</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import</em>'.
   * @generated
   */
  Import createImport();

  /**
   * Returns a new object of class '<em>Pourcent vitesse hauteur max</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pourcent vitesse hauteur max</em>'.
   * @generated
   */
  Pourcent_vitesse_hauteur_max createPourcent_vitesse_hauteur_max();

  /**
   * Returns a new object of class '<em>Pourcent vitesse deplacement max</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pourcent vitesse deplacement max</em>'.
   * @generated
   */
  Pourcent_vitesse_deplacement_max createPourcent_vitesse_deplacement_max();

  /**
   * Returns a new object of class '<em>Pourcent vitesse rotation max</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pourcent vitesse rotation max</em>'.
   * @generated
   */
  Pourcent_vitesse_rotation_max createPourcent_vitesse_rotation_max();

  /**
   * Returns a new object of class '<em>Hauteur max</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Hauteur max</em>'.
   * @generated
   */
  Hauteur_max createHauteur_max();

  /**
   * Returns a new object of class '<em>Eloignement max</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Eloignement max</em>'.
   * @generated
   */
  Eloignement_max createEloignement_max();

  /**
   * Returns a new object of class '<em>Monter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Monter</em>'.
   * @generated
   */
  Monter createMonter();

  /**
   * Returns a new object of class '<em>Descendre</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Descendre</em>'.
   * @generated
   */
  Descendre createDescendre();

  /**
   * Returns a new object of class '<em>Avancer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Avancer</em>'.
   * @generated
   */
  Avancer createAvancer();

  /**
   * Returns a new object of class '<em>Reculer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reculer</em>'.
   * @generated
   */
  Reculer createReculer();

  /**
   * Returns a new object of class '<em>Gauche</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Gauche</em>'.
   * @generated
   */
  Gauche createGauche();

  /**
   * Returns a new object of class '<em>Droite</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Droite</em>'.
   * @generated
   */
  Droite createDroite();

  /**
   * Returns a new object of class '<em>Pause</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pause</em>'.
   * @generated
   */
  Pause createPause();

  /**
   * Returns a new object of class '<em>Rotation Gauche</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rotation Gauche</em>'.
   * @generated
   */
  RotationGauche createRotationGauche();

  /**
   * Returns a new object of class '<em>Rotation Droite</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rotation Droite</em>'.
   * @generated
   */
  RotationDroite createRotationDroite();

  /**
   * Returns a new object of class '<em>Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement</em>'.
   * @generated
   */
  Statement createStatement();

  /**
   * Returns a new object of class '<em>Fonction Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fonction Decl</em>'.
   * @generated
   */
  FonctionDecl createFonctionDecl();

  /**
   * Returns a new object of class '<em>Pourcent Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pourcent Decl</em>'.
   * @generated
   */
  PourcentDecl createPourcentDecl();

  /**
   * Returns a new object of class '<em>Int Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Int Decl</em>'.
   * @generated
   */
  IntDecl createIntDecl();

  /**
   * Returns a new object of class '<em>Pourcent Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pourcent Exp</em>'.
   * @generated
   */
  PourcentExp createPourcentExp();

  /**
   * Returns a new object of class '<em>Ref Int Var</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ref Int Var</em>'.
   * @generated
   */
  RefIntVar createRefIntVar();

  /**
   * Returns a new object of class '<em>Ref Pourcent Var</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ref Pourcent Var</em>'.
   * @generated
   */
  RefPourcentVar createRefPourcentVar();

  /**
   * Returns a new object of class '<em>Int Constante</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Int Constante</em>'.
   * @generated
   */
  IntConstante createIntConstante();

  /**
   * Returns a new object of class '<em>Int Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Int Exp</em>'.
   * @generated
   */
  IntExp createIntExp();

  /**
   * Returns a new object of class '<em>Fonction Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fonction Call</em>'.
   * @generated
   */
  FonctionCall createFonctionCall();

  /**
   * Returns a new object of class '<em>MD</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MD</em>'.
   * @generated
   */
  MD createMD();

  /**
   * Returns a new object of class '<em>GDr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>GDr</em>'.
   * @generated
   */
  GDr createGDr();

  /**
   * Returns a new object of class '<em>RGRD</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RGRD</em>'.
   * @generated
   */
  RGRD createRGRD();

  /**
   * Returns a new object of class '<em>AR</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AR</em>'.
   * @generated
   */
  AR createAR();

  /**
   * Returns a new object of class '<em>Parallele2</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parallele2</em>'.
   * @generated
   */
  Parallele2 createParallele2();

  /**
   * Returns a new object of class '<em>Parallele3</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parallele3</em>'.
   * @generated
   */
  Parallele3 createParallele3();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  DroneDSLPackage getDroneDSLPackage();

} //DroneDSLFactory
