/**
 * generated by Xtext 2.12.0
 */
package fr.idmteam1.idmproject.dronedsl.droneDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Main</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.idmteam1.idmproject.dronedsl.droneDSL.Main#getDecollage <em>Decollage</em>}</li>
 *   <li>{@link fr.idmteam1.idmproject.dronedsl.droneDSL.Main#getMainbody <em>Mainbody</em>}</li>
 *   <li>{@link fr.idmteam1.idmproject.dronedsl.droneDSL.Main#getAtterrissage <em>Atterrissage</em>}</li>
 *   <li>{@link fr.idmteam1.idmproject.dronedsl.droneDSL.Main#getFdm <em>Fdm</em>}</li>
 * </ul>
 *
 * @see fr.idmteam1.idmproject.dronedsl.droneDSL.DroneDSLPackage#getMain()
 * @model
 * @generated
 */
public interface Main extends EObject
{
  /**
   * Returns the value of the '<em><b>Decollage</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Decollage</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decollage</em>' containment reference.
   * @see #setDecollage(Decoller)
   * @see fr.idmteam1.idmproject.dronedsl.droneDSL.DroneDSLPackage#getMain_Decollage()
   * @model containment="true"
   * @generated
   */
  Decoller getDecollage();

  /**
   * Sets the value of the '{@link fr.idmteam1.idmproject.dronedsl.droneDSL.Main#getDecollage <em>Decollage</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decollage</em>' containment reference.
   * @see #getDecollage()
   * @generated
   */
  void setDecollage(Decoller value);

  /**
   * Returns the value of the '<em><b>Mainbody</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mainbody</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mainbody</em>' containment reference list.
   * @see fr.idmteam1.idmproject.dronedsl.droneDSL.DroneDSLPackage#getMain_Mainbody()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getMainbody();

  /**
   * Returns the value of the '<em><b>Atterrissage</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Atterrissage</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atterrissage</em>' containment reference.
   * @see #setAtterrissage(Atterrir)
   * @see fr.idmteam1.idmproject.dronedsl.droneDSL.DroneDSLPackage#getMain_Atterrissage()
   * @model containment="true"
   * @generated
   */
  Atterrir getAtterrissage();

  /**
   * Sets the value of the '{@link fr.idmteam1.idmproject.dronedsl.droneDSL.Main#getAtterrissage <em>Atterrissage</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Atterrissage</em>' containment reference.
   * @see #getAtterrissage()
   * @generated
   */
  void setAtterrissage(Atterrir value);

  /**
   * Returns the value of the '<em><b>Fdm</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fdm</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fdm</em>' containment reference.
   * @see #setFdm(FinDeMain)
   * @see fr.idmteam1.idmproject.dronedsl.droneDSL.DroneDSLPackage#getMain_Fdm()
   * @model containment="true"
   * @generated
   */
  FinDeMain getFdm();

  /**
   * Sets the value of the '{@link fr.idmteam1.idmproject.dronedsl.droneDSL.Main#getFdm <em>Fdm</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fdm</em>' containment reference.
   * @see #getFdm()
   * @generated
   */
  void setFdm(FinDeMain value);

} // Main
