/**
 * generated by Xtext 2.12.0
 */
package fr.idmteam1.idmproject.dronedsl.droneDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pourcent Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.idmteam1.idmproject.dronedsl.droneDSL.DroneDSLPackage#getPourcentExp()
 * @model
 * @generated
 */
public interface PourcentExp extends EObject
{
} // PourcentExp
