/**
 * generated by Xtext 2.12.0
 */
package org.roboticiens.idmProject.validation;

import org.roboticiens.idmProject.validation.AbstractDroneMainValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DroneMainValidator extends AbstractDroneMainValidator {
}
