/**
 * generated by Xtext 2.12.0
 */
package org.roboticiens.idmProject.droneMain.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.roboticiens.idmProject.droneMain.AR;
import org.roboticiens.idmProject.droneMain.DroneMainPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>AR</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ARImpl extends MinimalEObjectImpl.Container implements AR
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ARImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DroneMainPackage.Literals.AR;
  }

} //ARImpl
