/**
 * generated by Xtext 2.12.0
 */
package org.roboticiens.idmProject.droneMain.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.roboticiens.idmProject.droneMain.DroneMainPackage;
import org.roboticiens.idmProject.droneMain.GDr;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>GDr</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GDrImpl extends MinimalEObjectImpl.Container implements GDr
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GDrImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DroneMainPackage.Literals.GDR;
  }

} //GDrImpl
