/**
 * generated by Xtext 2.12.0
 */
package org.roboticiens.idmProject.droneMain.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.roboticiens.idmProject.droneMain.DroneMainPackage;
import org.roboticiens.idmProject.droneMain.PourcentExp;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pourcent Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PourcentExpImpl extends MinimalEObjectImpl.Container implements PourcentExp
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PourcentExpImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DroneMainPackage.Literals.POURCENT_EXP;
  }

} //PourcentExpImpl
