/*
 * generated by Xtext 2.12.0
 */
package fr.idmteam1.idmproject.dronedsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDroneDSLScopeProvider extends DelegatingScopeProvider {
}
