/**
 * generated by Xtext 2.12.0
 */
package org.roboticiens.idmProject.ui.contentassist;

import org.roboticiens.idmProject.ui.contentassist.AbstractDroneMainProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DroneMainProposalProvider extends AbstractDroneMainProposalProvider {
}
