/*
 * generated by Xtext 2.12.0
 */
package org.roboticiens.idmProject.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDroneMainScopeProvider extends DelegatingScopeProvider {
}
