/**
 * generated by Xtext 2.12.0
 */
package fr.idmteam1.idmproject.dronedsl.validation;

import fr.idmteam1.idmproject.dronedsl.validation.AbstractDroneDSLLibValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DroneDSLLibValidator extends AbstractDroneDSLLibValidator {
}
