/**
 * generated by Xtext 2.12.0
 */
package fr.idmteam1.idmproject.dronedsl.scoping;

import fr.idmteam1.idmproject.dronedsl.scoping.AbstractDroneDSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class DroneDSLScopeProvider extends AbstractDroneDSLScopeProvider {
}
