/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.MyTurtleDslRuntimeModule;
import org.xtext.example.mydsl.MyTurtleDslStandaloneSetup;
import org.xtext.example.mydsl.ide.MyTurtleDslIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MyTurtleDslIdeSetup extends MyTurtleDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    MyTurtleDslRuntimeModule _myTurtleDslRuntimeModule = new MyTurtleDslRuntimeModule();
    MyTurtleDslIdeModule _myTurtleDslIdeModule = new MyTurtleDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_myTurtleDslRuntimeModule, _myTurtleDslIdeModule));
  }
}
